version: 2
builds:
  - id: csvlinter
    main: ./main.go
    binary: csvlinter
    goos: [darwin, linux, windows]
    goarch: [amd64, arm64]
    # optional: disable CGO for static binaries
    env:
      - CGO_ENABLED=0

archives:
  - id: binaries
    name_template: "{{ .ProjectName }}-{{ .Os }}-{{ .Arch }}"

homebrew_casks:
  - name: csvlinter
    repository:
      owner: csvlinter
      name: homebrew-tap
    directory: Formula
    commit_author:
      name: goreleaser-bot
      email: ci@users.noreply.github.com
    commit_msg_template: |
      chore(brew): bump {{ .FormulaName }} to {{ .Version }}
    homepage:  https://github.com/csvlinter/csvlinter
    description: "Streaming CSV validator with JSON-Schema support"